const cases=[
{t:'Caso 01 — Memória desaparecida',img:'hipocampo.png',q:'Qual estrutura está fortemente associada à consolidação de novas memórias?',a:['Hipocampo','Bulbo','Ponte','Medula'],ok:0,clue:'Pista 1 coletada: fragmento superior esquerdo da fotografia.',who:'helena.png',name:'Dra. Helena',intro:'Detetive, examine a evidência. A memória é a primeira chave deste caso.',hit:'Excelente. Você recuperou o primeiro fragmento da fotografia.'},
{t:'Caso 02 — O relevo cortical',img:'cortex.png',q:'A camada superficial de substância cinzenta do cérebro corresponde principalmente ao:',a:['Córtex cerebral','Corpo caloso','Tálamo','Aqueduto cerebral'],ok:0,clue:'Pista 2 coletada: novo fragmento facial recuperado.',who:'caio.png',name:'Dr. Caio',intro:'Observe giros, sulcos e a superfície cerebral. Não se deixe distrair.',hit:'Boa análise. Mais uma parte do rosto foi recuperada.'},
{t:'Caso 03 — Central de retransmissão',img:'talamo.png',q:'Qual estrutura do diencéfalo funciona como importante estação de retransmissão sensorial?',a:['Tálamo','Hipocampo','Cerebelo','Medula'],ok:0,clue:'Pista 3 coletada: a fotografia começa a ganhar forma.',who:'rafael.png',name:'Dr. Rafael',intro:'Esta pista está escondida em uma estrutura profunda. Qual é a central de retransmissão?',hit:'Confirmado. Já temos três fragmentos do suspeito.'},
{t:'Caso 04 — Reflexos e vias',img:'mesencefalo.png',q:'O mesencéfalo pertence a qual grande conjunto anatômico?',a:['Tronco encefálico','Telencéfalo','Cerebelo','Medula espinal'],ok:0,clue:'Pista 4 coletada: metade da fotografia está quase identificável.',who:'maia.png',name:'Perita Maia',intro:'Siga o neuroeixo. Esta evidência pode mudar o rumo da investigação.',hit:'Você conectou a evidência corretamente. O quarto fragmento está no quadro.'},
{t:'Caso 05 — Via central',img:'medula.png',q:'A medula espinal localiza-se principalmente dentro do:',a:['Canal vertebral','Seio sagital','Meato acústico','Forame obturado'],ok:0,clue:'Pista 5 coletada: detalhes importantes do suspeito aparecem.',who:'helena.png',name:'Dra. Helena',intro:'A pista percorre a coluna. Localize com precisão onde a medula está protegida.',hit:'Perfeito. O quinto pedaço da fotografia foi recuperado.'},
{t:'Caso 06 — Conexão hemisférica',img:'corpo-caloso.png',q:'Qual estrutura é a maior comissura que conecta os hemisférios cerebrais?',a:['Corpo caloso','Hipotálamo','Quiasma óptico','Hipocampo'],ok:0,clue:'Pista 6 coletada: falta apenas um fragmento para completar o rosto.',who:'caio.png',name:'Dr. Caio',intro:'Duas metades, uma grande conexão. Encontre a comissura principal.',hit:'Conexão estabelecida. Só falta uma evidência.'},
{t:'Caso 07 — Evidência posterior',img:'occipital.png',q:'Qual lobo cerebral ocupa predominantemente a região posterior do cérebro e está relacionado ao processamento visual?',a:['Lobo occipital','Lobo frontal','Lobo temporal','Ínsula'],ok:0,clue:'Pista 7 coletada: fotografia completa liberada.',who:'rafael.png',name:'Dr. Rafael',intro:'Última evidência. Olhe para a região posterior e encerre o caso.',hit:'Caso fechado. Os sete fragmentos formam agora uma única fotografia.'}
];
let i=0,score=0,sound=true,timer=45,intv;const $=s=>document.querySelector(s);
const sfx={acerto:new Audio('assets/audio/acerto.mp3'),erro:new Audio('assets/audio/erro.mp3'),poder:new Audio('assets/audio/poder.mp3'),vitoria:new Audio('assets/audio/vitoria.mp3')};Object.values(sfx).forEach(a=>{a.preload='auto';a.volume=.8});
function playSfx(name){if(!sound||!sfx[name])return;const a=sfx[name];a.currentTime=0;a.play().catch(()=>{})}
const suspectPhoto='assets/img/maia.png';
function buildPhoto(el,revealed=0){el.innerHTML=''; for(let x=0;x<7;x++){const d=document.createElement('div');d.className='photo-piece'+(x<revealed?' revealed':'');d.style.backgroundImage=`url(${suspectPhoto})`;d.style.setProperty('--piece',x);d.setAttribute('aria-label',x<revealed?`Fragmento ${x+1} coletado`:`Fragmento ${x+1} bloqueado`);el.append(d)}}
function talk(c,line){$('#characterImg').src='assets/img/'+c.who;$('#characterName').textContent=c.name;$('#characterLine').textContent=line;$('#characterTalk').classList.remove('speak');void $('#characterTalk').offsetWidth;$('#characterTalk').classList.add('speak')}
function logEvidence(){const log=$('#evidenceLog');log.innerHTML='';for(let x=0;x<score;x++){const s=document.createElement('span');s.textContent='📸 '+(x+1);s.title='Fragmento fotográfico '+(x+1)+' coletado';log.append(s)}}
buildPhoto($('#mosaic'),0);
function render(){clearInterval(intv);timer=45;$('#phase').textContent=i+1;$('#evn').textContent=String(i+1).padStart(2,'0');$('#score').textContent=score;let c=cases[i];$('#caseTitle').textContent=c.t;$('#question').textContent=c.q;$('#qimg').src='assets/img/'+c.img;$('#qimg').alt='Evidência visual da '+c.t;$('#answers').innerHTML='';c.a.forEach((x,n)=>{let b=document.createElement('button');b.className='answer';b.textContent=String.fromCharCode(65+n)+') '+x;b.onclick=()=>answer(n,b);$('#answers').append(b)});$('#feedback').textContent='';talk(c,c.intro);$('#timer').textContent='00:45';intv=setInterval(()=>{timer--;$('#timer').textContent='00:'+String(timer).padStart(2,'0');if(timer<=0){clearInterval(intv);$('#feedback').textContent='⏱ Tempo encerrado. Analise novamente a evidência.';talk(c,'O tempo acabou, mas a investigação continua. Releia a evidência e tente novamente.');document.querySelectorAll('.answer').forEach(x=>x.dataset.done='') ;timer=45}},1000)}
function answer(n,b){if(b.dataset.done)return;let c=cases[i];if(n===c.ok){document.querySelectorAll('.answer').forEach(x=>x.dataset.done=1);score++;playSfx('acerto');setTimeout(()=>playSfx('poder'),220);$('#feedback').innerHTML='✅ EVIDÊNCIA CONFIRMADA — um pedaço real da fotografia foi coletado.';$('#clueText').textContent=c.clue;buildPhoto($('#mosaic'),score);logEvidence();talk(c,c.hit);setTimeout(()=>{i++;if(i<cases.length)render();else finish()},2200)}else{playSfx('erro');b.classList.add('wrong');b.disabled=true;$('#feedback').innerHTML='❌ Hipótese descartada. Este fragmento ainda está bloqueado. Tente outra alternativa.';talk(c,'Essa hipótese não fecha com a evidência. Observe novamente e tente outra resposta.')}}
function finish(){clearInterval(intv);$('#game').hidden=true;$('#end').hidden=false;buildPhoto($('#finalMosaic'),7);$('#suspect').textContent='Fotografia reconstruída: Perita Maia';$('#finalTalk').innerHTML='<img src="assets/img/helena.png" alt="Dra. Helena"><div><b>Dra. Helena</b><p>Detetive, as sete evidências foram reunidas. Você reconstruiu a fotografia completa e solucionou o Arquivo Neural.</p></div>';playSfx('vitoria')}
$('#start').onclick=()=>{$('#intro').hidden=true;$('#game').hidden=false;render()};$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=sound?'🔊 Som':'🔇 Som'};$('#contrast').onclick=()=>document.body.classList.toggle('high');$('#font').onclick=()=>document.body.classList.toggle('big');$('#libras').onclick=()=>$('#librasPanel').hidden=false;$('#closeLibras').onclick=()=>$('#librasPanel').hidden=true;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
let deferredInstallPrompt=null;const installBtn=$('#installApp');const installHelp=$('#installHelp');window.addEventListener('beforeinstallprompt',(e)=>{e.preventDefault();deferredInstallPrompt=e;installBtn.hidden=false;installHelp.textContent='Aplicativo pronto para instalar. Toque em INSTALAR APLICATIVO.'});installBtn.addEventListener('click',async()=>{if(!deferredInstallPrompt){installHelp.textContent='Abra o menu do navegador e escolha “Instalar app” ou “Adicionar à tela inicial”.';return}deferredInstallPrompt.prompt();const choice=await deferredInstallPrompt.userChoice;if(choice.outcome==='accepted')installHelp.textContent='Instalação iniciada.';deferredInstallPrompt=null;installBtn.hidden=true});window.addEventListener('appinstalled',()=>{installBtn.hidden=true;installHelp.textContent='✓ NeuroDetetive instalado como aplicativo.'});
